import turtle
t=turtle.Turtle()
t.begin_fill()
t.color("green")
t.circle(100)
t.end_fill()
#Eye number 1
t.penup()
t.left(90)
t.forward(130)
t.begin_fill()
t.color("white")
t.circle(30)
t.end_fill()
t.backward(10)
t.left(90)
t.forward(10)
t.right(90)
t.begin_fill()
t.color("black")
t.circle(20)
t.end_fill()
#Eye number 2
t.forward(10)
t.right(90)
t.forward(70)
t.left(90)
t.begin_fill()
t.color("white")
t.circle(30)
t.end_fill()
t.backward(10)
t.left(90)
t.forward(10)
t.right(90)
t.begin_fill()
t.color("black")
t.circle(20)
t.end_fill()

#Mouth
t.color("black")
t.pensize(10)
t.backward(50)
t.left(90)
t.backward(20)
t.pendown()
t.forward(135)

t.hideturtle()

#Nose
#t.backward(10)
#t.left(90)
#t.forward(50)
#t.begin_fill()
#t.color("orange")
#t.circle(25)
#t.end_fill()
#t.left(90)
#t.forward(60)
#t.left(90)
#t.forward(50)
#t.color("black")
#t.pensize(10)
#t.pendown()
#t.left(180)
#t.forward(90)
